/**
 * Documents repository — org-scoped. Every query is constrained to the org the
 * repo was constructed with (see {@link OrgScopedRepository}), so a handler can
 * never read or mutate another tenant's documents.
 */
import type { Document, DocumentStatus } from '@clouddocs/shared-types';

import type { TxClient } from '../lib/db/client';
import { OrgScopedRepository } from './org-scoped-repository';

// A type alias (not interface) so it satisfies the `Record<string, unknown>`
// constraint on OrgScopedRepository.scopedQuery — interfaces can't be assigned
// to an index signature, type aliases of object types can.
export type DocumentRow = {
  id: string;
  org_id: string;
  uploaded_by: string;
  filename: string;
  mime_type: string;
  size_bytes: string; // BIGINT comes back as a string from node-postgres
  s3_key: string;
  status: DocumentStatus;
  error: string | null;
  text_s3_key: string | null;
  page_count: number | null;
  language: string | null;
  category: string | null;
  tags: string[];
  metadata: Record<string, unknown>;
  created_at: Date;
  updated_at: Date;
};

export interface CreateDocumentInput {
  /** Generated by the caller so the S3 key can embed it before insert. */
  id: string;
  uploadedBy: string;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  s3Key: string;
}

export class DocumentsRepo extends OrgScopedRepository {
  /** Insert a new `pending_upload` row and return it. */
  async create(input: CreateDocumentInput, tx?: TxClient): Promise<DocumentRow> {
    const rows = await this.scopedQuery<DocumentRow>(
      `INSERT INTO documents (id, org_id, uploaded_by, filename, mime_type, size_bytes, s3_key)
       VALUES ($2, $1, $3, $4, $5, $6, $7)
       RETURNING *`,
      [input.id, input.uploadedBy, input.filename, input.mimeType, input.sizeBytes, input.s3Key],
      tx,
    );
    const row = rows[0];
    if (!row) throw new Error('Insert into documents returned no row.');
    return row;
  }

  async findById(id: string): Promise<DocumentRow | undefined> {
    const rows = await this.scopedQuery<DocumentRow>(
      'SELECT * FROM documents WHERE org_id = $1 AND id = $2',
      [id],
    );
    return rows[0];
  }

  /** Transition a document to a new status (e.g. `uploaded`, `failed`). */
  async setStatus(
    id: string,
    status: DocumentStatus,
    error?: string,
  ): Promise<DocumentRow | undefined> {
    const rows = await this.scopedQuery<DocumentRow>(
      `UPDATE documents SET status = $3, error = $4
       WHERE org_id = $1 AND id = $2
       RETURNING *`,
      [id, status, error ?? null],
    );
    return rows[0];
  }

  /**
   * Atomically claim a document for extraction: pending_upload|uploaded →
   * extracting. Returns the row if this call won the claim, undefined if it was
   * already claimed/processed (idempotency + race-safety against duplicate S3
   * events and the client's /complete call).
   */
  async claimForExtraction(id: string): Promise<DocumentRow | undefined> {
    const rows = await this.scopedQuery<DocumentRow>(
      `UPDATE documents SET status = 'extracting'
       WHERE org_id = $1 AND id = $2 AND status IN ('pending_upload', 'uploaded')
       RETURNING *`,
      [id],
    );
    return rows[0];
  }

  /** Record extraction output and move to `extracted` (extract worker). */
  async markExtracted(
    id: string,
    input: { textS3Key: string; pageCount?: number; language?: string },
  ): Promise<DocumentRow | undefined> {
    const rows = await this.scopedQuery<DocumentRow>(
      `UPDATE documents
         SET status = 'extracted', text_s3_key = $3, page_count = $4, language = COALESCE($5, language)
       WHERE org_id = $1 AND id = $2
       RETURNING *`,
      [id, input.textS3Key, input.pageCount ?? null, input.language ?? null],
    );
    return rows[0];
  }

  /** Move `extracted` → `analyzing` (first analyze worker to run; idempotent). */
  async markAnalyzing(id: string): Promise<void> {
    await this.scopedQuery(
      `UPDATE documents SET status = 'analyzing'
       WHERE org_id = $1 AND id = $2 AND status = 'extracted'`,
      [id],
    );
  }

  /** Persist the classifier output onto the document (classify worker). */
  async setClassification(
    id: string,
    input: { category: string; tags: string[] },
  ): Promise<DocumentRow | undefined> {
    const rows = await this.scopedQuery<DocumentRow>(
      `UPDATE documents SET category = $3, tags = $4
       WHERE org_id = $1 AND id = $2
       RETURNING *`,
      [id, input.category, input.tags],
    );
    return rows[0];
  }

  /** Set the detected document language (summarize worker). */
  async setLanguage(id: string, language: string): Promise<void> {
    await this.scopedQuery(`UPDATE documents SET language = $3 WHERE org_id = $1 AND id = $2`, [
      id,
      language,
    ]);
  }

  /**
   * Atomically flips the document to `ready` once at least `requiredCount`
   * distinct analysis kinds exist for it. Idempotent and race-safe: the worker
   * that commits its analysis last is the one whose call sees the full set and
   * wins; earlier calls match zero rows. Returns true if it set `ready`.
   */
  async markReadyIfAnalysesComplete(
    id: string,
    kinds: readonly string[],
    requiredCount: number,
  ): Promise<boolean> {
    const rows = await this.scopedQuery<{ id: string }>(
      `UPDATE documents SET status = 'ready'
       WHERE org_id = $1 AND id = $2 AND status <> 'ready'
         AND (
           SELECT count(DISTINCT kind) FROM ai_analyses
           WHERE document_id = $2 AND org_id = $1 AND kind = ANY($3)
         ) >= $4
       RETURNING id`,
      [id, kinds as string[], requiredCount],
    );
    return rows.length > 0;
  }

  /**
   * Keyset pagination, newest first, with optional full-text search (`q` over
   * filename+category+tags) and status/category filters. Fetches one extra row
   * to know whether more exist without a second count query. The WHERE clause is
   * built dynamically; `$1` is always the org id (prepended by scopedQuery).
   */
  async list(opts: {
    limit: number;
    cursor?: string;
    q?: string;
    status?: DocumentStatus;
    category?: string;
  }): Promise<{ rows: DocumentRow[]; nextCursor: string | null }> {
    const where = ['org_id = $1'];
    const params: unknown[] = [];
    let p = 1;
    const add = (value: unknown): string => {
      params.push(value);
      return `$${++p}`;
    };

    if (opts.q) where.push(`search_tsv @@ websearch_to_tsquery('simple', ${add(opts.q)})`);
    if (opts.status) where.push(`status = ${add(opts.status)}`);
    if (opts.category) where.push(`category = ${add(opts.category)}`);
    if (opts.cursor) {
      where.push(
        `(created_at, id) < (SELECT created_at, id FROM documents WHERE id = ${add(opts.cursor)} AND org_id = $1)`,
      );
    }
    const limitPlaceholder = add(opts.limit + 1);

    const rows = await this.scopedQuery<DocumentRow>(
      `SELECT * FROM documents
       WHERE ${where.join(' AND ')}
       ORDER BY created_at DESC, id DESC
       LIMIT ${limitPlaceholder}`,
      params,
    );

    const hasMore = rows.length > opts.limit;
    const page = hasMore ? rows.slice(0, opts.limit) : rows;
    return { rows: page, nextCursor: hasMore ? (page[page.length - 1]?.id ?? null) : null };
  }

  /** Aggregate counters + a 14-day uploads series for the dashboard. */
  async getStats(): Promise<{
    total: number;
    ready: number;
    processing: number;
    failed: number;
    storageBytes: number;
    uploadsPerDay: Array<{ date: string; count: number }>;
  }> {
    const agg = await this.scopedQuery<{
      total: string;
      ready: string;
      processing: string;
      failed: string;
      bytes: string;
    }>(
      `SELECT
         count(*) AS total,
         count(*) FILTER (WHERE status = 'ready') AS ready,
         count(*) FILTER (WHERE status = 'failed') AS failed,
         count(*) FILTER (WHERE status NOT IN ('ready', 'failed')) AS processing,
         coalesce(sum(size_bytes), 0) AS bytes
       FROM documents WHERE org_id = $1`,
    );
    const series = await this.scopedQuery<{ date: string; count: string }>(
      `SELECT to_char(d::date, 'YYYY-MM-DD') AS date, coalesce(c.count, 0) AS count
       FROM generate_series(current_date - interval '13 days', current_date, interval '1 day') AS d
       LEFT JOIN (
         SELECT created_at::date AS day, count(*) AS count
         FROM documents WHERE org_id = $1 GROUP BY 1
       ) c ON c.day = d::date
       ORDER BY d`,
    );
    const a = agg[0];
    return {
      total: Number(a?.total ?? 0),
      ready: Number(a?.ready ?? 0),
      processing: Number(a?.processing ?? 0),
      failed: Number(a?.failed ?? 0),
      storageBytes: Number(a?.bytes ?? 0),
      uploadsPerDay: series.map((r) => ({ date: r.date, count: Number(r.count) })),
    };
  }
}

/** Map a DB row to the API/shared-types `Document` shape. */
export function toDocument(row: DocumentRow): Document {
  return {
    id: row.id,
    orgId: row.org_id,
    uploadedBy: row.uploaded_by,
    filename: row.filename,
    mimeType: row.mime_type,
    sizeBytes: Number(row.size_bytes),
    status: row.status,
    error: row.error,
    category: row.category,
    tags: row.tags ?? [],
    language: row.language,
    pageCount: row.page_count,
    createdAt: new Date(row.created_at).toISOString(),
    updatedAt: new Date(row.updated_at).toISOString(),
  };
}
